import type { Conversation, Message, Movie, Post, Profile } from "./types";

export const MOCK_MOVIES: Movie[] = [
  {
    id: "m1",
    title: "Interstellar",
    year: 2014,
    genres: ["Sci-Fi", "Adventure"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_url:
      "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    synopsis: "A journey beyond time and space.",
    rating: 8.6,
    trailer_url: null,
  },
  {
    id: "m2",
    title: "The Dark Knight",
    year: 2008,
    genres: ["Action", "Drama"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_url: null,
    synopsis: "Gotham's hero faces its darkest test.",
    rating: 9.0,
    trailer_url: null,
  },
  {
    id: "m3",
    title: "Spirited Away",
    year: 2001,
    genres: ["Animation", "Fantasy"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop_url: null,
    synopsis: "A girl lost in a world of spirits.",
    rating: 8.6,
    trailer_url: null,
  },
  {
    id: "m4",
    title: "Inception",
    year: 2010,
    genres: ["Sci-Fi", "Thriller"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop_url: null,
    synopsis: "A thief who steals corporate secrets through dreams.",
    rating: 8.8,
    trailer_url: null,
  },
  {
    id: "m5",
    title: "The Martian",
    year: 2015,
    genres: ["Sci-Fi", "Drama"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/5aGhaIHIcAKr0kAgt6RXCFbjW1G.jpg",
    backdrop_url: null,
    synopsis: "Stranded on Mars, an astronaut must survive.",
    rating: 8.0,
    trailer_url: null,
  },
  {
    id: "m6",
    title: "Dune",
    year: 2021,
    genres: ["Sci-Fi"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop_url: null,
    synopsis: "A hero's journey on the desert planet Arrakis.",
    rating: 8.0,
    trailer_url: null,
  },
  {
    id: "m7",
    title: "The Matrix",
    year: 1999,
    genres: ["Sci-Fi"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_url: null,
    synopsis: "A hacker discovers the truth of his reality.",
    rating: 8.7,
    trailer_url: null,
  },
  {
    id: "m8",
    title: "Your Name.",
    year: 2016,
    genres: ["Romance", "Animation"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
    backdrop_url: null,
    synopsis: "Two strangers swap bodies across time.",
    rating: 8.4,
    trailer_url: null,
  },
  {
    id: "m9",
    title: "The Prestige",
    year: 2006,
    genres: ["Drama", "Mystery"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/tRNlZbgNCNOpLpbPEz5L8TNEHPo.jpg",
    backdrop_url: null,
    synopsis: "Two rival magicians, one deadly obsession.",
    rating: 8.5,
    trailer_url: null,
  },
  {
    id: "m10",
    title: "Whiplash",
    year: 2014,
    genres: ["Drama", "Music"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_url: null,
    synopsis: "A drummer pushed to his limits by a ruthless instructor.",
    rating: 8.5,
    trailer_url: null,
  },
  {
    id: "m11",
    title: "Parasite",
    year: 2019,
    genres: ["Thriller", "Drama"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_url: null,
    synopsis: "Two families, one house, a class divide.",
    rating: 8.5,
    trailer_url: null,
  },
  {
    id: "m12",
    title: "The Grand Budapest Hotel",
    year: 2014,
    genres: ["Comedy", "Drama"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    backdrop_url: null,
    synopsis: "A concierge and his protégé navigate a hotel's mysteries.",
    rating: 8.1,
    trailer_url: null,
  },
  {
    id: "m13",
    title: "The Shawshank Redemption",
    year: 1994,
    genres: ["Drama"],
    poster_url:
      "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop_url: null,
    synopsis: "Hope is a dangerous, necessary thing.",
    rating: 9.3,
    trailer_url: null,
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: "u1",
    username: "olivia_wilson",
    display_name: "Olivia Wilson",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Sci-Fi", "Horror", "Comedy", "Thriller", "Rom-Com"],
    created_at: new Date().toISOString(),
  },
  {
    id: "u2",
    username: "emma_r",
    display_name: "Emma",
    avatar_url: "https://images.unsplash.com/photo-1520785643438-5bf77931f493?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Drama", "Romance"],
    created_at: new Date().toISOString(),
  },
  {
    id: "u3",
    username: "noah_k",
    display_name: "Noah",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Action", "Sci-Fi"],
    created_at: new Date().toISOString(),
  },
  {
    id: "u4",
    username: "ava_m",
    display_name: "Ava",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Rom-Com", "Comedy"],
    created_at: new Date().toISOString(),
  },
  {
    id: "u5",
    username: "liam_c",
    display_name: "Liam",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Thriller", "Mystery"],
    created_at: new Date().toISOString(),
  },
  {
    id: "u6",
    username: "sophia_l",
    display_name: "Sophia",
    avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
    cover_avatar_url: null,
    bio: null,
    genre_prefs: ["Drama"],
    created_at: new Date().toISOString(),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    is_group: false,
    title: null,
    updated_at: new Date(Date.now() - 2 * 60e3).toISOString(),
    participants: [MOCK_PROFILES[1]],
    last_message: {
      id: "msg1",
      conversation_id: "c1",
      sender_id: "u2",
      body: "Hey! Are we still on for tonight?",
      created_at: new Date(Date.now() - 2 * 60e3).toISOString(),
      read_at: null,
    },
    unread_count: 1,
  },
  {
    id: "c2",
    is_group: false,
    title: null,
    updated_at: new Date(Date.now() - 3600e3).toISOString(),
    participants: [MOCK_PROFILES[2]],
    last_message: {
      id: "msg2",
      conversation_id: "c2",
      sender_id: "u3",
      body: "That movie was amazing!",
      created_at: new Date(Date.now() - 3600e3).toISOString(),
      read_at: null,
    },
    unread_count: 1,
  },
  {
    id: "c3",
    is_group: false,
    title: null,
    updated_at: new Date(Date.now() - 3 * 3600e3).toISOString(),
    participants: [MOCK_PROFILES[3]],
    last_message: {
      id: "msg3",
      conversation_id: "c3",
      sender_id: "u4",
      body: "Thanks for the recommendation 💜",
      created_at: new Date(Date.now() - 3 * 3600e3).toISOString(),
      read_at: new Date().toISOString(),
    },
    unread_count: 0,
  },
  {
    id: "c4",
    is_group: false,
    title: null,
    updated_at: new Date(Date.now() - 5 * 3600e3).toISOString(),
    participants: [MOCK_PROFILES[4]],
    last_message: {
      id: "msg4",
      conversation_id: "c4",
      sender_id: "u5",
      body: "See you soon!",
      created_at: new Date(Date.now() - 5 * 3600e3).toISOString(),
      read_at: new Date().toISOString(),
    },
    unread_count: 0,
  },
  {
    id: "c5",
    is_group: false,
    title: null,
    updated_at: new Date(Date.now() - 86400e3).toISOString(),
    participants: [MOCK_PROFILES[5]],
    last_message: {
      id: "msg5",
      conversation_id: "c5",
      sender_id: "u6",
      body: "Let me know what you think",
      created_at: new Date(Date.now() - 86400e3).toISOString(),
      read_at: new Date().toISOString(),
    },
    unread_count: 0,
  },
];

export const MOCK_MESSAGES: Record<string, Message[]> = {
  c1: [
    {
      id: "msg1-a",
      conversation_id: "c1",
      sender_id: "u1",
      body: "Hey! Still on for the movie tonight?",
      created_at: new Date(Date.now() - 20 * 60e3).toISOString(),
      read_at: new Date().toISOString(),
    },
    {
      id: "msg1",
      conversation_id: "c1",
      sender_id: "u2",
      body: "Hey! Are we still on for tonight?",
      created_at: new Date(Date.now() - 2 * 60e3).toISOString(),
      read_at: null,
    },
  ],
  c2: [
    {
      id: "msg2-a",
      conversation_id: "c2",
      sender_id: "u1",
      body: "Did you catch Interstellar yet?",
      created_at: new Date(Date.now() - 2 * 3600e3).toISOString(),
      read_at: new Date().toISOString(),
    },
    {
      id: "msg2",
      conversation_id: "c2",
      sender_id: "u3",
      body: "That movie was amazing!",
      created_at: new Date(Date.now() - 3600e3).toISOString(),
      read_at: null,
    },
  ],
};

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    user_id: "u1",
    image_urls: [
      "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?w=800",
    ],
    caption: null,
    created_at: new Date(Date.now() - 2 * 3600e3).toISOString(),
    like_count: 1200,
    comment_count: 128,
    share_count: 64,
    bookmark_count: 40,
    author: MOCK_PROFILES[0],
  },
  {
    id: "p2",
    user_id: "u1",
    image_urls: [
      "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=800",
    ],
    caption: null,
    created_at: new Date(Date.now() - 5 * 3600e3).toISOString(),
    like_count: 892,
    comment_count: 74,
    share_count: 39,
    bookmark_count: 21,
    author: MOCK_PROFILES[0],
  },
  {
    id: "p3",
    user_id: "u1",
    image_urls: [
      "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
    ],
    caption: null,
    created_at: new Date(Date.now() - 1 * 86400e3).toISOString(),
    like_count: 2100,
    comment_count: 156,
    share_count: 98,
    bookmark_count: 55,
    author: MOCK_PROFILES[0],
  },
];

export const GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Sci-Fi",
  "Horror",
  "Thriller",
  "Rom-Com",
  "Animation",
  "Mystery",
];
